### PR TITLE
use cobra to implement command like k8s and update config file

### PR DESCRIPTION
**Pull request by duanjiong**
remove useless file in config
remove useless cm in manager.yaml
update porter.yaml

Signed-off-by: Duan Jiong <djduanjiong@gmail.com>

### CODE REVIEW

**Comment by zheng1** [comment]
Should we update the version in the deployment? 
```
image: kubespheredev/porter:v0.1.1
```

**Comment by duanjiong** [comment]
> Should we update the version in the deployment?
> 
> ```
> image: kubespheredev/porter:v0.1.1
> ```

Yes, but i have no permission.

**Pull request merged**
