### PR TITLE
Support muti arch image

### PR DESCRIPTION
**Pull request by duanjiong**
amd64 & arm64

Signed-off-by: Duan Jiong <djduanjiong@gmail.com>

### CODE REVIEW

**Comment by duanjiong** [comment]
fix #126

**Comment by zheng1** [comment]
I think we should also add buildx into github actions https://github.com/docker/build-push-action#usage
https://github.com/kubesphere/porter/runs/1342576657

**Comment by duanjiong** [comment]
> I think we should also add buildx into github actions https://github.com/docker/build-push-action#usage
> https://github.com/kubesphere/porter/runs/1342576657

Of course we should, but we don't have CICD now, so it's not a good idea to add it now. We should improve it first.

**Pull request merged**
